//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Translator.Desktop.Foundation.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string dbPassword {
            get {
                return ((string)(this["dbPassword"]));
            }
            set {
                this["dbPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.21")]
        public string version {
            get {
                return ((string)(this["version"]));
            }
            set {
                this["version"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string language {
            get {
                return ((string)(this["language"]));
            }
            set {
                this["language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Users\\\\")]
        public string template_path {
            get {
                return ((string)(this["template_path"]));
            }
            set {
                this["template_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Users\\\\")]
        public string translation_path {
            get {
                return ((string)(this["translation_path"]));
            }
            set {
                this["translation_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string story_path {
            get {
                return ((string)(this["story_path"]));
            }
            set {
                this["story_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string recents_0 {
            get {
                return ((string)(this["recents_0"]));
            }
            set {
                this["recents_0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string recents_1 {
            get {
                return ((string)(this["recents_1"]));
            }
            set {
                this["recents_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string recents_2 {
            get {
                return ((string)(this["recents_2"]));
            }
            set {
                this["recents_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string recents_3 {
            get {
                return ((string)(this["recents_3"]));
            }
            set {
                this["recents_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string recents_4 {
            get {
                return ((string)(this["recents_4"]));
            }
            set {
                this["recents_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool displayVAHints {
            get {
                return ((bool)(this["displayVAHints"]));
            }
            set {
                this["displayVAHints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool autoLoadRecent {
            get {
                return ((bool)(this["autoLoadRecent"]));
            }
            set {
                this["autoLoadRecent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool autoSave {
            get {
                return ((bool)(this["autoSave"]));
            }
            set {
                this["autoSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool autoTranslate {
            get {
                return ((bool)(this["autoTranslate"]));
            }
            set {
                this["autoTranslate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool askForSaveDialog {
            get {
                return ((bool)(this["askForSaveDialog"]));
            }
            set {
                this["askForSaveDialog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool alsoSaveToGame {
            get {
                return ((bool)(this["alsoSaveToGame"]));
            }
            set {
                this["alsoSaveToGame"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int recent_index {
            get {
                return ((int)(this["recent_index"]));
            }
            set {
                this["recent_index"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool autoLoadRecentIndex {
            get {
                return ((bool)(this["autoLoadRecentIndex"]));
            }
            set {
                this["autoLoadRecentIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool useFalseFolder {
            get {
                return ((bool)(this["useFalseFolder"]));
            }
            set {
                this["useFalseFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool enableDiscordRP {
            get {
                return ((bool)(this["enableDiscordRP"]));
            }
            set {
                this["enableDiscordRP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool enableCustomStories {
            get {
                return ((bool)(this["enableCustomStories"]));
            }
            set {
                this["enableCustomStories"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:05:00")]
        public global::System.TimeSpan autoSaveInterval {
            get {
                return ((global::System.TimeSpan)(this["autoSaveInterval"]));
            }
            set {
                this["autoSaveInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("user")]
        public string dbUserName {
            get {
                return ((string)(this["dbUserName"]));
            }
            set {
                this["dbUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool updateSettings {
            get {
                return ((bool)(this["updateSettings"]));
            }
            set {
                this["updateSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public float idealLength {
            get {
                return ((float)(this["idealLength"]));
            }
            set {
                this["idealLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int coloringDepth {
            get {
                return ((int)(this["coloringDepth"]));
            }
            set {
                this["coloringDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ignoreCustomStoryWarning {
            get {
                return ((bool)(this["ignoreCustomStoryWarning"]));
            }
            set {
                this["ignoreCustomStoryWarning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128, 255, 255")]
        public global::System.Drawing.Color nodeItemColor {
            get {
                return ((global::System.Drawing.Color)(this["nodeItemColor"]));
            }
            set {
                this["nodeItemColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 192, 192")]
        public global::System.Drawing.Color nodeItemGroupColor {
            get {
                return ((global::System.Drawing.Color)(this["nodeItemGroupColor"]));
            }
            set {
                this["nodeItemGroupColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 128, 0")]
        public global::System.Drawing.Color nodeActionColor {
            get {
                return ((global::System.Drawing.Color)(this["nodeActionColor"]));
            }
            set {
                this["nodeActionColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 255, 128")]
        public global::System.Drawing.Color nodeEventColor {
            get {
                return ((global::System.Drawing.Color)(this["nodeEventColor"]));
            }
            set {
                this["nodeEventColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fuchsia")]
        public global::System.Drawing.Color nodeCriterionColor {
            get {
                return ((global::System.Drawing.Color)(this["nodeCriterionColor"]));
            }
            set {
                this["nodeCriterionColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128, 128, 255")]
        public global::System.Drawing.Color nodeResponseColor {
            get {
                return ((global::System.Drawing.Color)(this["nodeResponseColor"]));
            }
            set {
                this["nodeResponseColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color nodeDialogueColor {
            get {
                return ((global::System.Drawing.Color)(this["nodeDialogueColor"]));
            }
            set {
                this["nodeDialogueColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 192, 255")]
        public global::System.Drawing.Color nodeDialogueFemaleOnlyColor {
            get {
                return ((global::System.Drawing.Color)(this["nodeDialogueFemaleOnlyColor"]));
            }
            set {
                this["nodeDialogueFemaleOnlyColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192, 192, 255")]
        public global::System.Drawing.Color nodeDialogueMaleOnlyColor {
            get {
                return ((global::System.Drawing.Color)(this["nodeDialogueMaleOnlyColor"]));
            }
            set {
                this["nodeDialogueMaleOnlyColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192, 0, 192")]
        public global::System.Drawing.Color nodeQuestColor {
            get {
                return ((global::System.Drawing.Color)(this["nodeQuestColor"]));
            }
            set {
                this["nodeQuestColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 224, 192")]
        public global::System.Drawing.Color nodeReactionColor {
            get {
                return ((global::System.Drawing.Color)(this["nodeReactionColor"]));
            }
            set {
                this["nodeReactionColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cyan")]
        public global::System.Drawing.Color nodeAchievementColor {
            get {
                return ((global::System.Drawing.Color)(this["nodeAchievementColor"]));
            }
            set {
                this["nodeAchievementColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 192")]
        public global::System.Drawing.Color nodeBGCColor {
            get {
                return ((global::System.Drawing.Color)(this["nodeBGCColor"]));
            }
            set {
                this["nodeBGCColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Purple")]
        public global::System.Drawing.Color nodeValueColor {
            get {
                return ((global::System.Drawing.Color)(this["nodeValueColor"]));
            }
            set {
                this["nodeValueColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Maroon")]
        public global::System.Drawing.Color nodeDoorColor {
            get {
                return ((global::System.Drawing.Color)(this["nodeDoorColor"]));
            }
            set {
                this["nodeDoorColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192, 192, 0")]
        public global::System.Drawing.Color nodeInventoryColor {
            get {
                return ((global::System.Drawing.Color)(this["nodeInventoryColor"]));
            }
            set {
                this["nodeInventoryColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color nodeStateColor {
            get {
                return ((global::System.Drawing.Color)(this["nodeStateColor"]));
            }
            set {
                this["nodeStateColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192, 0, 192")]
        public global::System.Drawing.Color nodePersonalityColor {
            get {
                return ((global::System.Drawing.Color)(this["nodePersonalityColor"]));
            }
            set {
                this["nodePersonalityColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 192, 192")]
        public global::System.Drawing.Color nodeCutsceneColor {
            get {
                return ((global::System.Drawing.Color)(this["nodeCutsceneColor"]));
            }
            set {
                this["nodeCutsceneColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192, 255, 192")]
        public global::System.Drawing.Color nodeClothingColor {
            get {
                return ((global::System.Drawing.Color)(this["nodeClothingColor"]));
            }
            set {
                this["nodeClothingColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192, 255, 255")]
        public global::System.Drawing.Color nodeCriteriaGroupColor {
            get {
                return ((global::System.Drawing.Color)(this["nodeCriteriaGroupColor"]));
            }
            set {
                this["nodeCriteriaGroupColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 128, 128")]
        public global::System.Drawing.Color nodePoseColor {
            get {
                return ((global::System.Drawing.Color)(this["nodePoseColor"]));
            }
            set {
                this["nodePoseColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color nodePropertyColor {
            get {
                return ((global::System.Drawing.Color)(this["nodePropertyColor"]));
            }
            set {
                this["nodePropertyColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lime")]
        public global::System.Drawing.Color nodeSocialColor {
            get {
                return ((global::System.Drawing.Color)(this["nodeSocialColor"]));
            }
            set {
                this["nodeSocialColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool useRainbowEdges {
            get {
                return ((bool)(this["useRainbowEdges"]));
            }
            set {
                this["useRainbowEdges"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("224, 224, 224")]
        public global::System.Drawing.Color nodeMovingColor {
            get {
                return ((global::System.Drawing.Color)(this["nodeMovingColor"]));
            }
            set {
                this["nodeMovingColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color nodeInfoColor {
            get {
                return ((global::System.Drawing.Color)(this["nodeInfoColor"]));
            }
            set {
                this["nodeInfoColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color nodeSelectedColor {
            get {
                return ((global::System.Drawing.Color)(this["nodeSelectedColor"]));
            }
            set {
                this["nodeSelectedColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Silver")]
        public global::System.Drawing.Color nodeDefaultColor {
            get {
                return ((global::System.Drawing.Color)(this["nodeDefaultColor"]));
            }
            set {
                this["nodeDefaultColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64, 64, 64")]
        public global::System.Drawing.Color edgeDefaultColor {
            get {
                return ((global::System.Drawing.Color)(this["edgeDefaultColor"]));
            }
            set {
                this["edgeDefaultColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool useRainbowNodes {
            get {
                return ((bool)(this["useRainbowNodes"]));
            }
            set {
                this["useRainbowNodes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool enableStoryExplorerEdit {
            get {
                return ((bool)(this["enableStoryExplorerEdit"]));
            }
            set {
                this["enableStoryExplorerEdit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100000")]
        public int explorerMaxEdgeCount {
            get {
                return ((int)(this["explorerMaxEdgeCount"]));
            }
            set {
                this["explorerMaxEdgeCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool showExtendedExplorerInfo {
            get {
                return ((bool)(this["showExtendedExplorerInfo"]));
            }
            set {
                this["showExtendedExplorerInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ignoreMissingLinesWarning {
            get {
                return ((bool)(this["ignoreMissingLinesWarning"]));
            }
            set {
                this["ignoreMissingLinesWarning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool showSearchHighlightTranslation {
            get {
                return ((bool)(this["showSearchHighlightTranslation"]));
            }
            set {
                this["showSearchHighlightTranslation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool showSearchHighlightComments {
            get {
                return ((bool)(this["showSearchHighlightComments"]));
            }
            set {
                this["showSearchHighlightComments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool highlightLanguages {
            get {
                return ((bool)(this["highlightLanguages"]));
            }
            set {
                this["highlightLanguages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool exportTranslationInMissingLines {
            get {
                return ((bool)(this["exportTranslationInMissingLines"]));
            }
            set {
                this["exportTranslationInMissingLines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool exportTemplateDiff {
            get {
                return ((bool)(this["exportTemplateDiff"]));
            }
            set {
                this["exportTemplateDiff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool centerNodeOnClick {
            get {
                return ((bool)(this["centerNodeOnClick"]));
            }
            set {
                this["centerNodeOnClick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowNewlines {
            get {
                return ((bool)(this["AllowNewlines"]));
            }
            set {
                this["AllowNewlines"] = value;
            }
        }
    }
}
