using System;
using System.Collections.Generic;

namespace Translator.Core.Helpers
{
    /// <summary>
    /// A Class providing a list of all short keys for languages, as well the String representation of it.
    /// </summary>
    public static class LanguageHelper
    {
        public class LanguageException : Exception
        {
            public LanguageException() : base("You need to enter or select a valid language first") { }
            public LanguageException(string message) : base(message) { }
        }

        /// <summary>
        /// A list of all currently supported languages in short form
        /// </summary>
        //place new languages here, plus add string representation
        public static readonly string[] ShortLanguages = {
            "aa",
            "ab",
            "ae",
            "af",
            "ak",
            "am",
            "an",
            "ar",
            "as",
            "av",
            "ay",
            "az",
            "ba",
            "be",
            "bg",
            "bh",
            "bi",
            "bm",
            "bn",
            "bo",
            "br",
            "bs",
            "ca",
            "ce",
            "ch",
            "co",
            "cr",
            "cs",
            "cu",
            "cv",
            "cy",
            "da",
            "de",
            "dv",
            "dz",
            "ee",
            "el",
            "en",
            "eo",
            "es",
            "et",
            "eu",
            "fa",
            "ff",
            "fi",
            "fj",
            "fo",
            "fr",
            "fy",
            "ga",
            "gd",
            "gl",
            "gn",
            "gu",
            "gv",
            "ha",
            "he",
            "hi",
            "ho",
            "hr",
            "ht",
            "hu",
            "hy",
            "hz",
            "ia",
            "id",
            "ie",
            "ig",
            "ii",
            "ik",
            "io",
            "is",
            "it",
            "iu",
            "ja",
            "jv",
            "ka",
            "kg",
            "ki",
            "kj",
            "kk",
            "kl",
            "km",
            "kn",
            "ko",
            "kr",
            "ks",
            "ku",
            "kv",
            "kw",
            "ky",
            "la",
            "lb",
            "lg",
            "li",
            "ln",
            "lo",
            "lt",
            "lu",
            "lv",
            "mg",
            "mh",
            "mi",
            "mk",
            "ml",
            "mn",
            "mr",
            "ms",
            "mt",
            "my",
            "na",
            "nb",
            "nd",
            "ne",
            "ng",
            "nl",
            "nn",
            "no",
            "nr",
            "nv",
            "ny",
            "oc",
            "oj",
            "om",
            "or",
            "os",
            "pa",
            "pi",
            "pl",
            "ps",
            "pt",
            "qu",
            "rm",
            "rn",
            "ro",
            "ru",
            "rw",
            "sa",
            "sc",
            "sd",
            "se",
            "sg",
            "si",
            "sk",
            "sl",
            "sm",
            "sn",
            "so",
            "sq",
            "sr",
            "ss",
            "st",
            "su",
            "sv",
            "sw",
            "ta",
            "te",
            "tg",
            "th",
            "ti",
            "tk",
            "tl",
            "tn",
            "to",
            "tr",
            "ts",
            "tt",
            "tw",
            "ty",
            "uk",
            "ur",
            "uz",
            "ve",
            "vi",
            "vo",
            "wa",
            "wo",
            "xh",
            "yi",
            "yo",
            "za",
            "cn",
            "zu",
            "ptbr",
            "exmx"
        };

        /// <summary>
        /// A Dictionary with all String representations of the languages given in short form as the key
        /// </summary>
        public static readonly Dictionary<string, string> Languages = new() {
            {ShortLanguages[0], "Afar"},
            {ShortLanguages[1], "Abkhazian"},
            {ShortLanguages[2], "Avestan"},
            {ShortLanguages[3], "Afrikaans"},
            {ShortLanguages[4], "Akan"},
            {ShortLanguages[5], "Amharic"},
            {ShortLanguages[6], "Aragonese"},
            {ShortLanguages[7], "Arabic"},
            {ShortLanguages[8], "Assamese"},
            {ShortLanguages[9], "Avaric"},
            {ShortLanguages[10], "Aymara"},
            {ShortLanguages[11], "Azerbaijani"},
            {ShortLanguages[12], "Bashkir"},
            {ShortLanguages[13], "Belarusian"},
            {ShortLanguages[14], "Bulgarian"},
            {ShortLanguages[15], "Bihari languages"},
            {ShortLanguages[16], "Bislama"},
            {ShortLanguages[17], "Bambara"},
            {ShortLanguages[18], "Bengali"},
            {ShortLanguages[19], "Tibetan"},
            {ShortLanguages[20], "Breton"},
            {ShortLanguages[21], "Bosnian"},
            {ShortLanguages[22], "Catalan; Valencian"},
            {ShortLanguages[23], "Chechen"},
            {ShortLanguages[24], "Chamorro"},
            {ShortLanguages[25], "Corsican"},
            {ShortLanguages[26], "Cree"},
            {ShortLanguages[27], "Czech"},
            {ShortLanguages[28], "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic"},
            {ShortLanguages[29], "Chuvash"},
            {ShortLanguages[30], "Welsh"},
            {ShortLanguages[31], "Danish"},
            {ShortLanguages[32], "German"},
            {ShortLanguages[33], "Divehi; Dhivehi; Maldivian"},
            {ShortLanguages[34], "Dzongkha"},
            {ShortLanguages[35], "Ewe"},
            {ShortLanguages[36], "Greek"},
            {ShortLanguages[37], "English"},
            {ShortLanguages[38], "Esperanto"},
            {ShortLanguages[39], "Spanish; Castilian"},
            {ShortLanguages[40], "Estonian"},
            {ShortLanguages[41], "Basque"},
            {ShortLanguages[42], "Persian"},
            {ShortLanguages[43], "Fulah"},
            {ShortLanguages[44], "Finnish"},
            {ShortLanguages[45], "Fijian"},
            {ShortLanguages[46], "Faroese"},
            {ShortLanguages[47], "French"},
            {ShortLanguages[48], "Western "},
            {ShortLanguages[49], "Irish"},
            {ShortLanguages[50], "Gaelic; Scottish Gaelic"},
            {ShortLanguages[51], "Galician"},
            {ShortLanguages[52], "Guarani"},
            {ShortLanguages[53], "Gujarati"},
            {ShortLanguages[54], "Manx"},
            {ShortLanguages[55], "Hausa"},
            {ShortLanguages[56], "Hebrew"},
            {ShortLanguages[57], "Hindi"},
            {ShortLanguages[58], "Hiri Motu"},
            {ShortLanguages[59], "Croatian"},
            {ShortLanguages[60], "Haitian; Haitian Creole"},
            {ShortLanguages[61], "Hungarian"},
            {ShortLanguages[62], "Armenian"},
            {ShortLanguages[63], "Herero"},
            {ShortLanguages[64], "Interlingua"},
            {ShortLanguages[65], "Indonesian"},
            {ShortLanguages[66], "Interlingue; Occidental"},
            {ShortLanguages[67], "Igbo"},
            {ShortLanguages[68], "Sichuan Yi; Nuosu"},
            {ShortLanguages[69], "Inupiaq"},
            {ShortLanguages[70], "Ido"},
            {ShortLanguages[71], "Icelandic"},
            {ShortLanguages[72], "Italian"},
            {ShortLanguages[73], "Inuktitut"},
            {ShortLanguages[74], "Japanese"},
            {ShortLanguages[75], "Javanese"},
            {ShortLanguages[76], "Georgian"},
            {ShortLanguages[77], "Kongo"},
            {ShortLanguages[78], "Kikuyu; Gikuyu"},
            {ShortLanguages[79], "Kuanyama; Kwanyama"},
            {ShortLanguages[80], "Kazakh"},
            {ShortLanguages[81], "Kalaallisut; Greenlandic"},
            {ShortLanguages[82], "Central Khmer"},
            {ShortLanguages[83], "Kannada"},
            {ShortLanguages[84], "Korean"},
            {ShortLanguages[85], "Kanuri"},
            {ShortLanguages[86], "Kashmiri"},
            {ShortLanguages[87], "Kurdish"},
            {ShortLanguages[88], "Komi"},
            {ShortLanguages[89], "Cornish"},
            {ShortLanguages[90], "Kirghiz; Kyrgyz"},
            {ShortLanguages[91], "Latin"},
            {ShortLanguages[92], "Luxembourgish; Letzeburgesch"},
            {ShortLanguages[93], "Ganda"},
            {ShortLanguages[94], "Limburgan; Limburger; Limburgish"},
            {ShortLanguages[95], "Lingala"},
            {ShortLanguages[96], "Lao"},
            {ShortLanguages[97], "Lithuanian"},
            {ShortLanguages[98], "Luba-Katanga"},
            {ShortLanguages[99], "Latvian"},
            {ShortLanguages[100], "Malagasy"},
            {ShortLanguages[101], "Marshallese"},
            {ShortLanguages[102], "Maori"},
            {ShortLanguages[103], "Macedonian"},
            {ShortLanguages[104], "Malayalam"},
            {ShortLanguages[105], "Mongolian"},
            {ShortLanguages[106], "Marathi"},
            {ShortLanguages[107], "Malay"},
            {ShortLanguages[108], "Maltese"},
            {ShortLanguages[109], "Burmese"},
            {ShortLanguages[110], "Nauru"},
            {ShortLanguages[111], "Bokmål, Norwegian; Norwegian Bokmål"},
            {ShortLanguages[112], "Ndebele, North; North Ndebele"},
            {ShortLanguages[113], "Nepali"},
            {ShortLanguages[114], "Ndonga"},
            {ShortLanguages[115], "Dutch; Flemish"},
            {ShortLanguages[116], "Norwegian Nynorsk; Nynorsk, Norwegian"},
            {ShortLanguages[117], "Norwegian"},
            {ShortLanguages[118], "Ndebele, South; South Ndebele"},
            {ShortLanguages[119], "Navajo; Navaho"},
            {ShortLanguages[120], "Chichewa; Chewa; Nyanja"},
            {ShortLanguages[121], "Occitan"},
            {ShortLanguages[122], "Ojibwa"},
            {ShortLanguages[123], "Oromo"},
            {ShortLanguages[124], "Oriya"},
            {ShortLanguages[125], "Ossetian; Ossetic"},
            {ShortLanguages[126], "Panjabi; Punjabi"},
            {ShortLanguages[127], "Pali"},
            {ShortLanguages[128], "Polish"},
            {ShortLanguages[129], "Pushto; Pashto"},
            {ShortLanguages[130], "Portuguese"},
            {ShortLanguages[131], "Quechua"},
            {ShortLanguages[132], "Romansh"},
            {ShortLanguages[133], "Rundi"},
            {ShortLanguages[134], "Romanian; Moldavian; Moldovan"},
            {ShortLanguages[135], "Russian"},
            {ShortLanguages[136], "Kinyarwanda"},
            {ShortLanguages[137], "Sanskrit"},
            {ShortLanguages[138], "Sardinian"},
            {ShortLanguages[139], "Sindhi"},
            {ShortLanguages[140], "Northern Sami"},
            {ShortLanguages[141], "Sango"},
            {ShortLanguages[142], "Sinhala; Sinhalese"},
            {ShortLanguages[143], "Slovak"},
            {ShortLanguages[144], "Slovenian"},
            {ShortLanguages[145], "Samoan"},
            {ShortLanguages[146], "Shona"},
            {ShortLanguages[147], "Somali"},
            {ShortLanguages[148], "Albanian"},
            {ShortLanguages[149], "Serbian"},
            {ShortLanguages[150], "Swati"},
            {ShortLanguages[151], "Sotho, Southern"},
            {ShortLanguages[152], "Sundanese"},
            {ShortLanguages[153], "Swedish"},
            {ShortLanguages[154], "Swahili"},
            {ShortLanguages[155], "Tamil"},
            {ShortLanguages[156], "Telugu"},
            {ShortLanguages[157], "Tajik"},
            {ShortLanguages[158], "Thai"},
            {ShortLanguages[159], "Tigrinya"},
            {ShortLanguages[160], "Turkmen"},
            {ShortLanguages[161], "Tagalog"},
            {ShortLanguages[162], "Tswana"},
            {ShortLanguages[163], "Tonga"},
            {ShortLanguages[164], "Turkish"},
            {ShortLanguages[165], "Tsonga"},
            {ShortLanguages[166], "Tatar"},
            {ShortLanguages[167], "Twi"},
            {ShortLanguages[168], "Tahitian"},
            {ShortLanguages[169], "Ukrainian"},
            {ShortLanguages[170], "Urdu"},
            {ShortLanguages[171], "Uzbek"},
            {ShortLanguages[172], "Venda"},
            {ShortLanguages[173], "Vietnamese"},
            {ShortLanguages[174], "Volapük"},
            {ShortLanguages[175], "Walloon"},
            {ShortLanguages[176], "Wolof"},
            {ShortLanguages[177], "Xhosa"},
            {ShortLanguages[178], "Yiddish"},
            {ShortLanguages[179], "Yoruba"},
            {ShortLanguages[180], "Zhuang; Chuang"},
            {ShortLanguages[181], "Chinese"},
            {ShortLanguages[182], "Zulu"},
            {ShortLanguages[183], "Portuguese, Brazilian"},
            {ShortLanguages[184], "Spanish, Mexican"}
        };
    }
}
